
name: DistancePlace
version: ${version}
main: net.lulg.distanceplace.DistancePlace
api-version: 1.20
description: Distant block placement utilities. Use /reach command.
commands:
  reach:
    permission: distanceplace.use
    usage: /reach <blocks>|reset|status|speed|mode
permissions:
  distanceplace.use:
    default: true
